// Secciones y capítulos del Sistema Armonizado (TIGIE) — módulo compartido
// Extraído de seed-from-excel.ts para reutilizar en seed-ligie-2026.ts

export const SECTIONS: { number: string; title: string; chapters: string[] }[] = [
  { number: 'I', title: 'Animales vivos y productos del reino animal', chapters: ['01','02','03','04','05'] },
  { number: 'II', title: 'Productos del reino vegetal', chapters: ['06','07','08','09','10','11','12','13','14'] },
  { number: 'III', title: 'Grasas y aceites animales o vegetales', chapters: ['15'] },
  { number: 'IV', title: 'Productos de las industrias alimentarias; bebidas; tabaco', chapters: ['16','17','18','19','20','21','22','23','24'] },
  { number: 'V', title: 'Productos minerales', chapters: ['25','26','27'] },
  { number: 'VI', title: 'Productos de las industrias químicas', chapters: ['28','29','30','31','32','33','34','35','36','37','38'] },
  { number: 'VII', title: 'Plástico y caucho y sus manufacturas', chapters: ['39','40'] },
  { number: 'VIII', title: 'Pieles, cueros y sus manufacturas', chapters: ['41','42','43'] },
  { number: 'IX', title: 'Madera, corcho y sus manufacturas', chapters: ['44','45','46'] },
  { number: 'X', title: 'Pasta de madera, papel y cartón', chapters: ['47','48','49'] },
  { number: 'XI', title: 'Materias textiles y sus manufacturas', chapters: ['50','51','52','53','54','55','56','57','58','59','60','61','62','63'] },
  { number: 'XII', title: 'Calzado, sombreros, paraguas, plumas, flores artificiales', chapters: ['64','65','66','67'] },
  { number: 'XIII', title: 'Manufacturas de piedra, cerámica, vidrio', chapters: ['68','69','70'] },
  { number: 'XIV', title: 'Perlas, piedras preciosas, metales preciosos, bisutería', chapters: ['71'] },
  { number: 'XV', title: 'Metales comunes y sus manufacturas', chapters: ['72','73','74','75','76','78','79','80','81','82','83'] },
  { number: 'XVI', title: 'Máquinas, aparatos y material eléctrico', chapters: ['84','85'] },
  { number: 'XVII', title: 'Material de transporte', chapters: ['86','87','88','89'] },
  { number: 'XVIII', title: 'Instrumentos de óptica, medida, médicos; relojería; musicales', chapters: ['90','91','92'] },
  { number: 'XIX', title: 'Armas y municiones', chapters: ['93'] },
  { number: 'XX', title: 'Mercancías y productos diversos', chapters: ['94','95','96'] },
  { number: 'XXI', title: 'Objetos de arte o colección y antigüedades', chapters: ['97'] },
  { number: 'XXII', title: 'Operaciones especiales', chapters: ['98'] },
];

export const CHAPTER_NAMES: Record<string, string> = {
  '01': 'Animales vivos', '02': 'Carne y despojos comestibles', '03': 'Pescados y crustáceos',
  '04': 'Leche y productos lácteos; huevos; miel', '05': 'Los demás productos de origen animal',
  '06': 'Plantas vivas y floricultura', '07': 'Hortalizas, plantas, raíces y tubérculos',
  '08': 'Frutas y frutos comestibles', '09': 'Café, té, yerba mate y especias', '10': 'Cereales',
  '11': 'Productos de la molinería; malta; almidón', '12': 'Semillas y frutos oleaginosos',
  '13': 'Gomas, resinas y extractos vegetales', '14': 'Materias trenzables',
  '15': 'Grasas y aceites', '16': 'Preparaciones de carne, pescado',
  '17': 'Azúcares y confitería', '18': 'Cacao y sus preparaciones',
  '19': 'Preparaciones de cereales, harina, almidón; pastelería',
  '20': 'Preparaciones de hortalizas, frutas', '21': 'Preparaciones alimenticias diversas',
  '22': 'Bebidas, líquidos alcohólicos y vinagre', '23': 'Alimentos para animales',
  '24': 'Tabaco y sucedáneos', '25': 'Sal; piedras; yesos, cales y cementos',
  '26': 'Minerales metalíferos, escorias y cenizas', '27': 'Combustibles minerales, aceites minerales',
  '28': 'Productos químicos inorgánicos', '29': 'Productos químicos orgánicos',
  '30': 'Productos farmacéuticos', '31': 'Abonos', '32': 'Extractos curtientes; pinturas y barnices',
  '33': 'Aceites esenciales; perfumería, cosmética', '34': 'Jabón; preparaciones para lavar; velas',
  '35': 'Materias albuminoideas; colas; enzimas', '36': 'Pólvoras y explosivos; pirotecnia',
  '37': 'Productos fotográficos o cinematográficos', '38': 'Productos diversos de las industrias químicas',
  '39': 'Plástico y sus manufacturas', '40': 'Caucho y sus manufacturas',
  '41': 'Pieles y cueros', '42': 'Manufacturas de cuero; artículos de viaje',
  '43': 'Peletería y confecciones', '44': 'Madera y sus manufacturas',
  '45': 'Corcho y sus manufacturas', '46': 'Manufacturas de espartería o cestería',
  '47': 'Pasta de madera', '48': 'Papel y cartón', '49': 'Productos editoriales; textos',
  '50': 'Seda', '51': 'Lana y pelo fino', '52': 'Algodón',
  '53': 'Las demás fibras textiles vegetales', '54': 'Filamentos sintéticos o artificiales',
  '55': 'Fibras sintéticas discontinuas', '56': 'Guata, fieltro y tela sin tejer',
  '57': 'Alfombras', '58': 'Tejidos especiales', '59': 'Telas impregnadas',
  '60': 'Tejidos de punto', '61': 'Prendas de vestir, de punto',
  '62': 'Prendas de vestir, excepto de punto', '63': 'Artículos textiles confeccionados',
  '64': 'Calzado', '65': 'Sombreros y tocados', '66': 'Paraguas y bastones',
  '67': 'Plumas preparadas; flores artificiales', '68': 'Manufacturas de piedra, yeso, cemento',
  '69': 'Productos cerámicos', '70': 'Vidrio y sus manufacturas',
  '71': 'Perlas, piedras preciosas, metales preciosos, bisutería',
  '72': 'Fundición, hierro y acero', '73': 'Manufacturas de hierro o acero',
  '74': 'Cobre y sus manufacturas', '75': 'Níquel y sus manufacturas',
  '76': 'Aluminio y sus manufacturas', '78': 'Plomo y sus manufacturas',
  '79': 'Cinc y sus manufacturas', '80': 'Estaño y sus manufacturas',
  '81': 'Los demás metales comunes; cermets', '82': 'Herramientas y cuchillería',
  '83': 'Manufacturas diversas de metal común',
  '84': 'Máquinas, aparatos y artefactos mecánicos',
  '85': 'Máquinas, aparatos y material eléctrico',
  '86': 'Vehículos y material para vías férreas', '87': 'Vehículos automóviles, tractores',
  '88': 'Aeronaves y vehículos espaciales', '89': 'Barcos y artefactos flotantes',
  '90': 'Instrumentos de óptica, medida, médicos', '91': 'Aparatos de relojería',
  '92': 'Instrumentos musicales', '93': 'Armas, municiones',
  '94': 'Muebles; artículos de cama; iluminación; construcciones prefabricadas',
  '95': 'Juguetes, juegos y artículos para recreo o deporte', '96': 'Manufacturas diversas',
  '97': 'Objetos de arte o colección y antigüedades', '98': 'Operaciones especiales',
};

export function getSectionForChapter(ch: string): string {
  for (const s of SECTIONS) {
    if (s.chapters.includes(ch)) return s.number;
  }
  return 'XXII';
}
